@startuml MedicAlert-FHIR-IPS
Title "MedicAlert FHIR IPS structure"
skinparam BoxPadding 6
skinparam ParticipantPadding 1
skinparam roundcorner 5
skinparam sequenceArrowThickness 2
skinparam dpi 200

entity Bundle <<FHIR>> #SkyBlue {
    + **type** = document
    + **identifier**
    + **timestamp**
    -- References --
    + **entry:Composition** -> Composition
    + **entry:Patient** -> Patient
    + **entry:AllergyIntolerance** -> AllergyIntolerance
    + **entry:Condition** -> AllergyIntolerance
}

entity Composition <<FHIR>> #SkyBlue {
}

entity AllergyIntolerance <<FHIR>> #SkyBlue {
}

entity Condition <<FHIR>> #SkyBlue {   
}

entity Patient <<FHIR>> #SkyBlue {
   + **identifier:NHI**
   + **identifier:MedicAlert id**
   + **active**
   + **name**
   + **telecom**
   + **gender**
   + **birthDate**
   + **deceased[x]**
   + **address**
   + **contact**
   + **communication**
   + **managingOrganisation**
}

' Bundle contains other resources
Bundle o-- Composition
Bundle o-- Patient
Bundle o-- Condition
Bundle o-- AllergyIntolerance

' Resources Reference each other
Composition --> Patient
AllergyIntolerance --> Patient
Condition --> Patient

@enduml